[pytest]
; не выводить предупреждения
; выводить печать в тестах в консоль
;addopts = -s -Wignore
;addopts = -p no:warnings -s
# -- recommended but optional:
python_files = tests.py tests_*.py test_*.py *_tests.py
;log_format = %(asctime)s %(levelname)s %(message)s
;log_date_format = %Y-%m-%d %H:%M
addopts = --tb=short -s -vv

[pytest-watch]
; https://testmon.org/
; https://docs.pytest.org/en/6.2.x/reference.html#command-line-flags
;runner = pytest --picked --testmon --tb=short --no-header --create-db
runner = bash ptw.sh
;runner = pytest --picked --testmon --tb=short --no-header -q --verbosity=1 --show-capture=no --create-db
;runner = pytest --picked --testmon --tb=short --no-header --trace -q --verbosity=1 --show-capture=no
;beforerun = black .
;beforerun = mypy --explicit-package-bases --namespace-packages . & black .
;afterrun = bash -c 'ls -al'
beforerun = ruff format --exclude versions . -s && ruff check --exclude versions . --fix -s
